environment: prd-apps
applicationName: lms-service
data:
  aws.access-key: "${awsAccesskey}"
  aws.kms.loanAgreementStorage: "b880fc56-9651-4750-9229-5966f4667bd8"
  aws.kms.nocStorage: "18a5b1e3-d5fe-4cf5-ac76-b09feaf2e716"
  aws.kms.requestResponseLog: "18a5b1e3-d5fe-4cf5-ac76-b09feaf2e716"
  aws.region: "${awsRegion}"
  aws.secret-key: "${awsSecretkey}"
  doc.upload.bucket-name: "tl-partner-loan-docs-bucket"
  encryption.algorithm: "AES"
  encryption.key: "X9v$G2m!QpL4z@Kd"
  environment.name: "PROD"
  kyc-adaptor.api.base-url: "http://kyc-adapter-prd-apps-service.prd-apps:80"
  kyc-adaptor.api.initiate-vkyc: "/api/v1/kyc/vkyc/{clientId}"
  logging.level.root: "INFO"
  m2p.api.base-url: "https://lms.trillionloans.com/fineract-provider/api"
  m2p.api.ml.fetch-document-url: "https://lms.trillionloans.com/fineract-provider/api/v1/loanapplication/{loanApplicationId}/documents/{documentId}/attachment"
  m2p.auth.token: "Zbu_9bE_U-QJWMOeTjTfOoCM4Ls"
  m2p.fineract-tenant-id: "lms"
  notification-service.api.base-url: "http://notification-service-prd-apps-service.prd-apps:80"
  notification-service.api.send-bulk-sms: "/partners/api/v1/notification-service/send-bulk-notification"
  notification-service.api.send-sms: "/partners/api/v1/notification-service/send-notification"
  notification-service.batchSize: "1000"
  notification-service.portal-link: "https://customerportal.trillionloans.com/login"
  notification-service.restructure.sms-trigger-enabled: "true"
  notification-service.templates.ckyc-sms-template: "CKYC"
  notification-service.templates.loan-agreement-delivery-scheduler-days: "0"
  notification-service.templates.loan-agreement-delivery-template: "LOAN_AGREEMENT"
  notification-service.templates.loan-closure-scheduler-days: "4"
  notification-service.templates.loan-closure-template: "LOAN_CLOSURE"
  notification-service.templates.noc-delivery-scheduler-days: "5"
  notification-service.templates.noc-delivery-template: "NOC_DELIVERY"
  notification-service.templates.open-dpd-loan-template: "OPEN_DPD"
  notification-service.templates.re-kyc-sms-template: "RE_KYC"
  notification-service.templates.welcome-loan-agreement-whatsapp-template: "WELCOME_WP"
  notification-service.templates.welcome-sms-template: "WELCOME"
  notification.kafka.topic: "notification_messages"
  re-kyc.offsets.due-days: "90,30,7"
  re-kyc.offsets.overdue-days: "-30,-60,-90"
  restructure.reschedule-reason-id: "294"
  restructure.risk-validation.disbursement-end: "2025-10-31"
  restructure.risk-validation.disbursement-start: "2025-01-01"
  restructure.risk-validation.dpd-max-exclusive: "60"
  restructure.risk-validation.dpd-min: "10"
  restructure.risk-validation.dpd-reject-threshold: "90"
  restructure.risk-validation.min-paid-repayments: "30"
  restructure.risk-validation.reschedule-reason-id: "294"
  restructure.risk-validation.tenure-options: "120,180,270,360,450,540"
  restructure.tenure-buffer-days: "30"
  s3.bucket.loanAgreementStorage: "prod-tl-loan-aggrement-pdf-storage-bucket"
  s3.bucket.nocStorage: "tl-noc-prod"
  s3.bucket.requestResponseLog: "tl-req-resp-docs-prod"
  server.port: "8091"
  spring.kafka.bootstrap-servers: "b-2.tlkafkaproduction.4nwhvg.c4.kafka.ap-south-1.amazonaws.com:9092,b-1.tlkafkaproduction.4nwhvg.c4.kafka.ap-south-1.amazonaws.com:9092"
  spring.kafka.producer.acks: "all"
  spring.kafka.producer.compression-type: "gzip"
  spring.kafka.producer.max-block-ms: "3000"
  spring.kafka.producer.max-request-size: "50000000"
  spring.kafka.producer.request-timeout-ms: "3000"
  spring.kafka.topic.logging: "lms-logs-prod"
  spring.r2dbc.password: "${dbPassword}"
  spring.r2dbc.url: "r2dbc:postgresql://tl-psql-prod.trillionloans.com:5432/trillion?ssl=true&sslMode=require"
  spring.r2dbc.username: "${dbUserName}"
  spring.redis.database: "0"
  spring.redis.host: "tl-prod-redis-001.as5rkv.ng.0001.aps1.cache.amazonaws.com"
  spring.redis.password: ""
  spring.redis.port: "6379"
  springdoc.packagesToScan: "com.trillionloans.lms.controller"
  springdoc.serverUrl: "http://lms-service.trillionloans.stg"
  springdoc.show-actuator: "true"
  springdoc.swagger-ui.enabled: "true"
  springdoc.swagger-ui.path: "/swagger-ui"
