environment: prd-apps
applicationName: customer-portal-backend
data:
  app.encryption.enabled: "true"
  app.encryption.key: "w7vNhC2fTtWcUHs8XG1X4w=="
  authorization-service.api.base-url: "http://authorisation-service-prd-apps-service.prd-apps:80"
  base64-secret-key: "q1N7R5b5c9R2IcQjVwtGGw=="
  collection.api.base-url: "http://collection-service-prd-apps-service.prd-apps:80"
  disable.product-id: "11"
  environment.name: "PROD"
  file-upload.max-total-size: "10485760"
  freshdesk.api.base-url: "https://trillionloans.freshdesk.com"
  freshdesk.api.create-ticket.endpoint: "/api/v2/tickets"
  freshdesk.api.key: "sgbFcol7dlzVnwq6mp"
  freshdesk.api.ticket-category-field-endpoint: "/api/v2/admin/ticket_fields/1070001314279"
  img-path.trillion-logo: "src\\main\\resources\\images\\TrillionLoans-Logo.png"
  jwt-secret-key: "A31E8C6D5BF7E9A08C6D7E528A4F01B5E26C9D0F387E4A1B5C76D4E7A9081B5A3E28C76D7A08C6D5B7E9A0B4C76D8A4F012E5C6D9A"
  lms.api.base-url: "http://lms-service-prd-apps-service.prd-apps:80"
  logging.level.root: "INFO"
  los.api.base-url: "http://los-service-prd-apps-service.prd-apps:80"
  product-name-mapping.mapping.1: "Merchant Loan"
  product-name-mapping.mapping.10: "Vehicle Loan"
  product-name-mapping.mapping.11: "Vehicle Loan"
  product-name-mapping.mapping.12: "Term Loan"
  product-name-mapping.mapping.13: "Term Loan"
  product-name-mapping.mapping.14: "Term Loan"
  product-name-mapping.mapping.15: "Business Loan"
  product-name-mapping.mapping.16: "Business Loan"
  product-name-mapping.mapping.17: "Term Loan"
  product-name-mapping.mapping.18: "Term Loan"
  product-name-mapping.mapping.19: "Vehicle Loan"
  product-name-mapping.mapping.2: "Merchant Loan"
  product-name-mapping.mapping.20: "Term Loan"
  product-name-mapping.mapping.21: "Trade Finance"
  product-name-mapping.mapping.22: "Merchant Loan"
  product-name-mapping.mapping.23: "Term Loan"
  product-name-mapping.mapping.24: "Term Loan"
  product-name-mapping.mapping.25: "Personal Loan"
  product-name-mapping.mapping.26: "Personal Loan"
  product-name-mapping.mapping.27: "Personal Loan"
  product-name-mapping.mapping.3: "Term Loan"
  product-name-mapping.mapping.4: "Merchant Loan"
  product-name-mapping.mapping.5: "Merchant Loan"
  product-name-mapping.mapping.6: "Business Loan"
  product-name-mapping.mapping.7: "Business Loan"
  product-name-mapping.mapping.8: "Term Loan"
  product-name-mapping.mapping.9: "Term Loan"
  product.office.mapping.1: "BharatPe"
  product.office.mapping.10: "OTO"
  product.office.mapping.11: "NDX"
  product.office.mapping.12: "GOKWIK"
  product.office.mapping.13: "GOKWIK"
  product.office.mapping.14: "GOKWIK"
  product.office.mapping.15: "CredFlow"
  product.office.mapping.16: "CredFlow"
  product.office.mapping.17: "GETVANTAGE"
  product.office.mapping.18: "GETVANTAGE"
  product.office.mapping.19: "OTO"
  product.office.mapping.2: "BharatPe"
  product.office.mapping.20: "GOKWIK"
  product.office.mapping.21: "NinjaCart"
  product.office.mapping.22: "BharatPe"
  product.office.mapping.23: "NinjaCart"
  product.office.mapping.24: "NinjaCart"
  product.office.mapping.3: "NDX"
  product.office.mapping.4: "BharatPe"
  product.office.mapping.5: "BharatPe"
  product.office.mapping.6: "CredFlow"
  product.office.mapping.7: "CredFlow"
  product.office.mapping.8: "GETVANTAGE"
  product.office.mapping.9: "GETVANTAGE"
  redis.cache.details-ttl: "3600"
  redis.cache.time: "30"
  server.port: "8089"
  spring.redis.database: "0"
  spring.redis.host: "tl-prod-redis-001.as5rkv.ng.0001.aps1.cache.amazonaws.com"
  spring.redis.password: ""
  spring.redis.port: "6379"
  springdoc.packagesToScan: "com.trillionloans.customer_portal"
  springdoc.show-actuator: "true"
  springdoc.swagger-ui.enabled: "true"
  springdoc.swagger-ui.operationsSorter: "method"
  springdoc.swagger-ui.path: "/swagger-ui"
  springdoc.swagger-ui.tags-sorter: "alpha"
  springdoc.url: "Production Server - Trillion Loans Customer Portal"
