environment: prd-apps
applicationName: los-service
data:
  PLO1.api.base-url: https://consumer-lending-emi.bharatpemoney.com/
  PLO1.headers.Content-Type: application/json
  PLO1.headers.X-API-KEY: 46743b01-8ca2-4247-bfd0-08752401f8c8
  aadhar.xml.validity: '12'
  analytic-service.api.base-url: http://analytic-service-prd-apps-service.prd-apps:80
  application-rejection.codes.bre-expired: '420'
  application-rejection.codes.bre-fail: '415'
  application-rejection.codes.kyc-fail: '256'
  application-rejection.codes.partner-rejection: '416'
  application-rejection.codes.penny-drop: '441'
  assurekit.api.base-url: https://nonprod-api.assurekit.com/uat/ps
  assurekit.api.create-plan: /plans/create/CREDIT
  assurekit.auth.token: UFRSSUxMMjUwOTE5OkJuMVJCRGtETXJCQWFsREw1dnNQYlg4N01RVmxoWFRF
  aws.kms.loanAgreementStorage: b880fc56-9651-4750-9229-5966f4667bd8
  aws.kms.requestResponseLog: 18a5b1e3-d5fe-4cf5-ac76-b09feaf2e716
  #aws.kms.riskDataSqs.key: "${awsKmsRiskDataSqskey}"
  aws.region: ${awsRegion}
  bharatpe-products-config.products: ELO,ELTO,BPBL1,PLO1
  bharatpe.api.base-url: https://api-nbfc.bharatpe.in/lending/trillion/v1
  bharatpe.headers.Content-Type: application/json
  bharatpe.headers.client-id: ${bp.client.id}
  bharatpe.headers.client-secret: ${bp.client.secret}
  bharatpeemi.api.base-url: https://merchant-lending-emi.bharatpemoney.com/
  bharatpeemi.headers.Content-Type: application/json
  bharatpeemi.headers.X-API-KEY: a569a8e3-2069-4a19-9875-d6adf9a0666e
  cache.client-details.ttl-seconds: '86400'
  cache.digio-live-banks: '24'
  cache.digio-response.ttl-seconds: '86400'
  cache.opv-response.ttl-seconds: '86400'
  digio.api.base-url: https://api.digio.in
  digio.api.download-document: /v2/client/document/download
  digio.api.fetch-mandate: /v3/client/mandate/{mandateId}
  digio.api.live-banks: /v3/client/mandate/banks
  digio.api.login: https://app.digio.in/#/gateway/login
  digio.api.mandate-registration: /v3/client/mandate/create_form
  digio.api.upload-pdf: /v2/client/document/uploadpdf
  digio.auth.aml-pep-token: T1JHMjUwOTI1MTA0NjIwNDMwMTE4VERWRDE1N0RYVEM6UGFzc3dvcmRAMTIz
  digio.auth.token: QUlHOExXSUtaUlNQUjJSMUZBMjNZRlpEOUEzN0I5MkQ6S1RYQ1VBRjUxNFFIQlNRVzNTR1NESVc1QTNHR1RBNjY=
  digio.cutoff.threshold: '80'
  digio.enable-monitoring: 'false'
  digio.esigning.expire-in-days: '10'
  digio.esigning.identifier: tl.integrations@trillionloans.com
  digio.esigning.key-store-name: test
  digio.esigning.reason: TL LOAN AGREEMENT
  digio.external-signer.base-url: http://10.0.165.239:8080
  digio.external-signer.sign-document: /external_signer/signdoc
  digio.monitoring.frequency: '900'
  digio.response.mode: DETAILED
  digio.rules: RID260202185516982TKZ39OWV7XT4YG,RID260202184358055SUUF2PFL42HDJQ
  digio.screening.mode: SCREENING
  digio.screening.type: SCREEN_ONLY_RESPONSE
  doc-sign-service.api.base-url: http://doc-sign-service-prd-apps-service.prd-apps:80
  doc-sign-service.api.doc-details: /api/v1/doc-sign/save-rps-and-client-detail-request/clientId/{clientId}/loanId/{loanId}
  doc-sign-service.loanDataSave.check: 'false'
  doc.upload.bucket-name: tl-partner-loan-docs-bucket
  encryption.algorithm: AES
  encryption.key: X9v$G2m!QpL4z@Kd
  environment.name: PROD
  freo.api.base-url: https://app.moneytap.com
  fundly.api.base-url: https://api-v2.fundly.ai/credit-engine/api/v1/lender-integration
  fundly.headers.Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjcmVkaXRfZW5naW5lIiwiaWF0IjoxNzc0OTQ1NjUzLCJleHAiOjE4MDY1MDMyNTMsInJvbGVzIjpbXX0.VNIhdqdJzf9avqpeFWYD3__8hSbamc8inMTPItjKxZiYyCGFq7yaTVT1IotWkwe5Pw9_31UGazV7xmLASw2khjr_OimzysldH7uDDd4xGl3Kx0naCyRs0KdcSOKuBAuL0Q0ruBUSCYxsR5HmvqPgF4pe4M7WvZRtflqp8WIaAJT1lwRbQdhmnQ6pE6AKnookmIbsAVBPwlRbKBCrzuYzHRX-Dq3PR6PCZnxbLE-g9o7g8yiDTg039cteeELrZ-Uy3LLzUuuV0G2zfdZdq1NdpDIpZseKOxYj3D6K2zQXJtppK1G74sseiTOfaR-hkxMHwCNW_WtUsEvkVzWVBN6PJQ
  fundly.headers.Content-Type: application/json
  karza.api.base-url: https://api.karza.in
  karza.api.face-similarity: /v3/facesimilarity
  karza.api.name-similarity: /v3/name
  karza.api.pan-aadhaar: /v3/pan-aadhaar-link
  karza.api.pan-authenticate: /v2/pan
  karza.api.pan-profile: /v3/pan-profile
  karza.key: G32smjBhf0UlBzG
  kyc-adaptor.api.base-url: http://kyc-adapter-prd-apps-service.prd-apps:80
  kyc-adaptor.api.get-bu-gu: /partners/api/v1/account-aggregator/fetch-bank-gst-underwriting/{loanId}
  kyc-adaptor.api.vcip.notification: /api/v1/kyc/vcip-notification/{clientId}
  loansyncx.api.base-url: http://loan-syncx-service-prd-apps-service.prd-apps:80
  loansyncx.api.headers.Content-Type: application/json
  logging.level.root: INFO
  lsp.api.base-url: http://lsp-layer-prd-apps-service.prd-apps:80
  lsp.api.rejection-callback-uri: /callback/rejection
  lsp.api.closure-callback-uri: /callback/loan-closure
  m2p.api.base-url: https://lms.trillionloans.com/fineract-provider/api
  m2p.auth.token: Zbu_9bE_U-QJWMOeTjTfOoCM4Ls
  m2p.fineract-tenant-id: lms
  m2p.risk.codes.highId: '430'
  m2p.risk.codes.lowId: '432'
  m2p.risk.codes.mediumId: '431'
  m2p.risk.codes.uhrId: '433'
  mobikwik.api.base-url: https://lending.mobikwik.com/
  mobikwik.headers.Content-Type: application/json
  mobikwik.headers.x-apikey: 4I3s4K40U2mS
  moneyview.api.base-url: https://partner.whizdm.com/
  moneyview.headers.Content-Type: application/json
  moneyview.headers.x-api-key: PSOKeFc9kf3cS4o97jlMb31HoMonpnlN6vJMmZ6E
  nexus.api.base-url: http://nexus-backend-prd-apps-service.prd-apps:80
  nexus.api.bulk-fetch-risk-parameters: /v1/risk-parameters/{productKey}/bulk-fetch
  nexus.api.fetch-risk-parameters: /v1/risk-parameters/{productKey}/{loanApplicationId}
  nexus.api.get-color-code: /api/master-entity/pincode_master/fetch
  ninjacart.api.base-url: https://api.ninjacartservices.com
  ninjacart.headers.Content-Type: application/json
  nirafinance.api.base-url: https://s5nv4m7lbc.execute-api.ap-south-1.amazonaws.com/prod/
  nirafinance.headers.Content-Type: application/json
  notification-service.api.base-url: http://notification-service-prd-apps-service.prd-apps:80
  notification-service.api.send-sms: /partners/api/v1/notification-service/send-notification
  notification-service.templates.credit-line-drawdown-approved-template: FUNDLY_DRAWDOWN_AA
  notification-service.templates.credit-line-limit-approved-template: FUNDLY_LIMIT_LA
  notification-service.templates.lead-acknowledgement-template: LEAD_ACKNOWLEDGEMENT
  nsdl.api.url: https://opvapi.egov.proteantech.in/TIN/PanInquiryAPIBackEnd
  nsdl.cert.bucketName: nsdl-certificate
  nsdl.cert.key: prod-certificate.pfx
  nsdl.cert.password: '123456789'
  nsdl.user-id: V0318801
  oto.api.base-url: https://betaapi.otocapital.in/lenderservice/trillionloans
  oto.headers.Authorization: 92b5fac180c27d19a00cc40df80ed9a73ef87fa0
  oto.headers.Content-Type: application/json
  pan-aadhaar-linkage: 'true'
  product.elo.id: '5'
  product.elto.id: '2'
  rapipay.api.base-url: https://api.rapimoney.com/nis
  rapipay.headers.Authorization: tl&r*i#ab(lL+oansR@apipay
  rapipay.headers.Content-Type: application/json
  redis.encryption.enabled: 'true'
  risk-service.api.base-url: http://risk-service-prd-apps-service.prd-apps:80
  risk-service.api.bre-data: /internal/api/v1/bre-data/{loanId}
  risk-service.api.drawdown-bre-data: /internal/api/v1/drawdown/bre/{limitId}
  risk.categorisation.check: 'true'
  risk.dedupe.bp.dpd: '1'
  risk.dedupe.check: enable
  risk.dedupe.drawdown.check: 'true'
  risk.dedupe.drawdown.dpd: '0'
  risk.dedupe.nonBp.dpd: '0'
  risk.service: enable
  s3.bucket.loanAgreementStorage: prod-tl-loan-aggrement-pdf-storage-bucket
  s3.bucket.requestResponseLog: tl-req-resp-docs-prod
  #s3.bucket.riskDataSqs: "${s3BucketRiskDataSqs}"
  saveIn.api.base-url: https://cnpl.api.savein.money/
  saveIn.headers.Content-Type: application/json
  saveIn.headers.X-API-KEY: 7d02bfd9-b2cb-4ec2-8065-a3c0a342708e
  server.port: '8090'
  server.shutdown: graceful
  spring.codec.max-in-memory-size: 10MB
  spring.kafka.bootstrap-servers: b-2.tlkafkaproduction.4nwhvg.c4.kafka.ap-south-1.amazonaws.com:9092,b-1.tlkafkaproduction.4nwhvg.c4.kafka.ap-south-1.amazonaws.com:9092
  spring.kafka.producer.acks: all
  spring.kafka.producer.compression-type: gzip
  spring.kafka.producer.max-block-ms: '3000'
  spring.kafka.producer.max-request-size: '50000000'
  spring.kafka.producer.request-timeout-ms: '30000'
  spring.kafka.topic.event: loan_lifecycle_events
  spring.kafka.topic.loan-funnel: loan-funnel-prod
  spring.kafka.topic.logging: los-logs-prod
  spring.lifecycle.timeout-per-shutdown-phase: 30s
  spring.r2dbc.password: ${dbPassword}
  spring.r2dbc.pool.initial-size: '15'
  spring.r2dbc.pool.max-size: '20'
  spring.r2dbc.url: r2dbc:postgresql://tl-psql-prod.trillionloans.com:5432/trillion?ssl=true&sslMode=require
  spring.r2dbc.username: ${dbUserName}
  spring.redis.database: '0'
  spring.redis.host: tl-prod-redis-001.as5rkv.ng.0001.aps1.cache.amazonaws.com
  spring.redis.password: ''
  spring.redis.port: '6379'
  springdoc.packages-to-exclude: com.trillionloans.los.controller.internal
  springdoc.packagesToScan: com.trillionloans.los.controller
  springdoc.show-actuator: 'true'
  springdoc.swagger-ui.enabled: 'true'
  springdoc.swagger-ui.operationsSorter: method
  springdoc.swagger-ui.path: /swagger-ui
  springdoc.swagger-ui.tags-sorter: alpha
  springdoc.url: Production Server - Trillion Loans LOS
  #sqs.queue.riskDataSqs: "${sqsQueueRiskDataSqs}"
  store.codependent.flag: enable
  syntizen.api.apikey: '0'
  syntizen.api.authentication: /liveapi/sws/userauthentication
  syntizen.api.baseUrl: https://app.syntizen.com
  syntizen.api.ckycsearch: /liveapi/sws/CKYC_Search
  syntizen.api.disable-ssl-verification: 'true'
  throttle.per-second: '5'
  transaction-service.api.auto-disburse: /v1/payout/transfers
  transaction-service.api.base-url: http://bank-transaction-service-prd-apps-service.prd-apps:80
  transaction-service.api.get-auto-disburse-status: /v1/payout/transfers/{loanId}
  transaction-service.api.get-bank-verification-status: /v1/lead/{leadId}/verify-bank/{bankId}/status
  transaction-service.api.verify-bank: /v1/lead/{leadId}/loan/{loanId}/verify-bank
  validation-funnel.cache.enabled: 'true'
  validation-funnel.cache.encryption-enabled: 'false'
  validation-funnel.cache.ttl: '86400'
  validation-funnel.master-flag: 'true'
  web-client.timeout.extra-large: '120000'
  web-client.timeout.extra-small: '1000'
  web-client.timeout.large: '30000'
  web-client.timeout.medium: '30000'
  web-client.timeout.small: '5000'
