package com.trillionloans.los.constant;

import lombok.Getter;

@Getter
public enum DocumentTag {
  KFS("KFS"),
  LOAN_AGREEMENT("LOAN_AGREEMENT"),
  LOAN_AGREEMENT_NEW("LOAN_AGREEMENT_NEW"),
  RESCHEDULE_AGREEMENT("RESCHEDULE_AGREEMENT"),
  CONSENT("CONSENT"),
  KFS_NEW("KFS_NEW"),
  PROFORMA_INVOICE("PROFORMA_INVOICE"),
  DRIVING_LICENSE("DRIVING_LICENSE"),
  RC_COPY("RC_COPY"),
  INVOICE("INVOICE"),
  FI_REPORT("FI_REPORT"),
  CPV("CPV"),
  SELLER_DOCUMENT("SELLER_DOCUMENT"),
  INSURANCE("INSURANCE"),
  DO("DELIVERY_ORDER"),
  INSURANCE_DOCUMENT("INSURANCE_DOCUMENT"),
  LOAN_AGREEMENT_BNPL("LOAN_AGREEMENT_BNPL"),
  UDYAM_CERTIFICATE("UDYAM_CERTIFICATE"),
  GST_REGISTRATION_CERTIFICATE("GST_REGISTRATION_CERTIFICATE"),
  DRUG_LICENSE("DRUG_LICENSE"),
  DRAWDOWN_AGREEMENT("DRAWDOWN_AGREEMENT"),
  BUSINESS_DOC("BUSINESS_DOC");

  private final String displayName;

  DocumentTag(String displayName) {
    this.displayName = displayName;
  }
}
