apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-portal-frontend-config-customer-portal-frontend-prd-apps
data:
  REACT_APP_AUTH_ENDPOINT: "https://authorisation-service.trillionloans.com"
  REACT_APP_CUSTOMER_PORTAL_ENDPOINT: "https://customer-portal.trillionloans.com"
  REACT_APP_TRILLION_ENDPOINT: "https://www.trillionloans.com"
