spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5433/crm
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:db/seed_data.sql
      continue-on-error: false
